name: Package for Copr repo

on:
  push:
    paths:
      - COPR/**
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload-copr:
    strategy:
      fail-fast: false
      matrix:
        pkgname: [ swayfx, scenefx ]

    container: fedora:latest
    runs-on: ubuntu-latest
    needs: RPM-build
    steps:
      - name: Install API token for copr-cli
        env:
          # To generate a new token: https://copr.fedorainfracloud.org/api/.
          API_LOGIN: ${{ secrets.COPR_API_LOGIN }}
          API_USERNAME: ${{ secrets.COPR_API_USERNAME }}
          API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
        run: |
          mkdir -p "$HOME/.config"
          # To generate a new token: https://copr.fedorainfracloud.org/api/.
          echo "[copr-cli]" >> "$HOME/.config/copr"
          echo "login = $API_LOGIN" >> "$HOME/.config/copr"
          echo "username = $API_USERNAME" >> "$HOME/.config/copr"
          echo "token = $API_TOKEN_CONTENT" >> "$HOME/.config/copr"
          echo "copr_url = https://copr.fedorainfracloud.org" >> "$HOME/.config/copr"

      - name: Install dependencies
        run: |
          dnf -y install copr-cli

      - name: Check out sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Submit the build to copr
        run: |
          cd COPR/${{matrix.pkgname}}
          rpkg -v copr-build -w ${{ secrets.COPR_REPO_NAME }}
